"""
configs/config.py
Single source of truth for all paths and hyperparameters.
Update paths here before running any script.
"""

import os

# ─── PATHS ────────────────────────────────────────────────────────────────────

# Dataset directories (NTIRE 2026 official training set)
TRAIN_INPUT_DIR  = './data/train/input'
TRAIN_GT_DIR     = './data/train/gt'
VAL_INPUT_DIR    = './data/val/input'
VAL_GT_DIR       = './data/val/gt'       # set to None if GT not available
TEST_INPUT_DIR   = './data/test/input'

# Augmented patch dataset (generated by augment.py)
AUG_INPUT_DIR    = './data/augmented/input'
AUG_GT_DIR       = './data/augmented/ground_truth'

# Weights
WEIGHTS_DIR      = './weights'

# ─── AUGMENTATION ─────────────────────────────────────────────────────────────

AUG_TARGET_TOTAL = 9000
AUG_PATCH_SIZE   = 256
AUG_STRIDE       = 64      # smaller stride = more patches from 25 images

# ─── TRAINING (shared) ────────────────────────────────────────────────────────

BATCH_SIZE       = 8
NUM_WORKERS      = 2
EMA_DECAY        = 0.999

# ─── PHASE 1 — MixUp / CutMix + EMA ──────────────────────────────────────────

P1_LR            = 2e-4
P1_EPOCHS        = 10
P1_MIX_PROB      = 0.5
P1_CUTMIX_PROB   = 0.5
P1_OUTPUT        = 'finetuned_phase1_mixup_ema.pth'

# ─── PHASE 2 — Nighttime Domain Adaptation ───────────────────────────────────

P2_LR            = 5e-5
P2_EPOCHS        = 10
P2_NOISE_PROB    = 0.5
P2_GLOW_PROB     = 0.5
P2_OUTPUT        = 'finetuned_phase2_nighttime.pth'

# ─── PHASE 3 — High-Res 512×512 Polish + EMA ─────────────────────────────────

P3_LR            = 1e-5
P3_EPOCHS        = 8
P3_PATCH_SIZE    = 512
P3_BATCH_SIZE    = 2        # small batch to avoid OOM at 512x512
P3_ACCUM_STEPS   = 4        # effective batch = P3_BATCH_SIZE * P3_ACCUM_STEPS
P3_SUBSET        = 3000     # use this many patches from the augmented dataset
P3_OUTPUT        = 'finetuned_phase3_highres_ema.pth'

# ─── PHASE 4 — SSIM + Charbonnier Polish + EMA ───────────────────────────────

P4_LR            = 5e-6
P4_EPOCHS        = 10
P4_BATCH_SIZE    = 4
P4_SUBSET        = 4000
P4_SSIM_WEIGHT   = 0.2      # weight of SSIM term in combined loss
P4_OUTPUT        = 'finetuned_phase4_ssim_ema.pth'

# ─── INFERENCE / TTA ──────────────────────────────────────────────────────────

ALIGN            = 16       # pad images to multiples of this
TTA_FOLDS        = 8        # 8-fold geometric TTA
TILE_SIZE        = 512      # tile size for large image inference
TILE_OVERLAP     = 64       # overlap between tiles

# ─── CHARBONNIER LOSS ─────────────────────────────────────────────────────────

CHARB_EPS        = 1e-3
